# Generated by Django 5.0.6 on 2024-06-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vuelo', models.DateField(default='01-01-2020')),
            ],
        ),
        migrations.CreateModel(
            name='Tiquete',
            fields=[
                ('id_tiquete', models.AutoField(primary_key=True, serialize=False)),
                ('clase_tiquete', models.CharField(max_length=30)),
                ('asiento_tiquete', models.CharField(max_length=30)),
                ('valor_tiquete', models.IntegerField()),
                ('user_tiquete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiquetera.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('tiquete_reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiquetera.tiquete')),
                ('vuelo_reserva', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tiquetera.vuelo')),
            ],
        ),
    ]
